version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "30162:3000"
    depends_on:
      - backend
    env_file:
      - stack.env

  backend:
    build: ./backend
    ports:
      - "28130:3008"
