version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "12079:3000"
    depends_on:
      - backend
    networks:
      - nginxproxymanager_nginx-proxy-manager-nw

  backend:
    build: 
      context: ./backend
      args:
        - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "14625:3008"
    networks:
      - nginxproxymanager_nginx-proxy-manager-nw

networks:
  nginxproxymanager_nginx-proxy-manager-nw: 
    # external: true

