version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "30162:3000"
    depends_on:
      - backend
    env_file:
      - stack.env
    networks:
      - default

  backend:
    build: ./backend
    networks:
      - reverse-proxy-nw

networks:
  reverse-proxy-nw:
    external: true