version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      args:
        - api_url=${NEXT_PUBLIC_API_URL}
    ports:
      - "12079:3000"
    depends_on:
      - backend
    env_file:
      - stack.env
    networks:
      - backend-network
      - nginxproxymanager_nginx-proxy-manager-nw

  backend:
    build: 
      context: ./backend
      args:
        - frontend_url=${FRONTEND_URL}
    env_file:
      - stack.env
    ports:
      - "14625:3008"
    networks:
      - backend-network
      - nginxproxymanager_nginx-proxy-manager-nw

networks:
  backend-network:
    driver: bridge
  nginxproxymanager_nginx-proxy-manager-nw: 
    external: true

